### ISSUE TITLE
EncodeException Instruction of type void must not have a name

### ISSUE THREAD

**Issue by pe200012** [sdiehl/kaleidoscope#53]
Hi, I was doing chapter 3 of the tutorial with LLVM 9 but the part of function parameters seems to have issues:
```
ready> def f(x) 1;;
kaleidoscope-exe: EncodeException "Instruction of type void must not have a name: UnName 1 := Store {volatile = False, address = LocalReference (FloatingPointType {floatingPointType = DoubleFP}) (UnName 0), value = LocalReference (FloatingPointType {floatingPointType = DoubleFP}) (Name \"x\"), maybeAtomicity = Nothing, alignment = 0, metadata = []}"
```
I am able to locate the problem -- `codegenTop`:
```
codegenTop (AST.Function name args body) = do
  define double name fnargs bls
  where
    fnargs = toSig args

    bls = createBlocks
      $ execCodegen
      $ do
        entry <- addBlock entryBlockName
        setBlock entry
        forM_ args
          $ \a -> do
            var <- alloca double
            store var (local (Name (BSS.toShort (BS.pack a)))) -- <<< PROBLEM HERE
            assign a var
        cgen body >>= ret


instr :: Instruction -> Codegen Operand
instr ins = do
  n <- fresh
  let ref = UnName n
  blk <- current
  modifyBlock (blk { stack = ref := ins <| stack blk })
  return $ local ref

store :: Operand -> Operand -> Codegen Operand
store ptr val = instr $ Store False ptr val Nothing 0 []
```
Why is this happening?

stack.yaml:
```
resolver: lts-18.28
packages:
- .
```

package.yaml:
```
dependencies:
- base >= 4.7 && < 5
- llvm-hs == 9.0.1
- llvm-hs-pure == 9.0.0
- parsec
- haskeline
- containers
- unordered-containers
- mtl
- bytestring
- lens

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  kaleidoscope-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kaleidoscope

tests:
  kaleidoscope-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kaleidoscope
```
